version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: etc/dev/Dockerfile
    volumes:
      - .:/home/dev/app
      - devhome:/home/dev
    ports:
      - "1323:1323"
      - "2345:2345"
volumes:
  devhome:
